spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password:
    url: jdbc:mysql://127.0.0.1:3306/tarot
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl_auto: create-drop
logging:
  level:
    org:
      hibernate:
        type: trace
